django_video/curated_videos/urls.py
from django.conf.urls import url
from .views import (HomePageView, CategoryListingView,
                    ConferenceListingView, SpeakerListingView)


urlpatterns = [
    url(r'^$', HomePageView.as_view()),
    url(r'^category/(?P<slug>[\w-]+)$', CategoryListingView.as_view(),
        name='category-listing'),
    url(r'^conference/(?P<slug>[\w-]+)$', ConferenceListingView.as_view(),
        name='conference-listing'),
    url(r'^speaker/(?P<id>\d+)$', SpeakerListingView.as_view(),
        name='speaker-listing'),
]

django_video/django_video/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    # Admin
    url(r'^admin/', admin.site.urls),

    url(r'^about$', TemplateView.as_view(template_name="about.html"), name='about'),
    url(r'^', include('curated_videos.urls', namespace="curated_videos")),


]

django_video/curated_videos/models.py
from django.db import models
from model_utils.models import TimeStampedModel


class Speaker(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    email = models.EmailField(max_length=450, blank=True, null=True)

    github_handle = models.CharField(
        max_length=200, blank=True, null=True)
    twitter_handle = models.CharField(max_length=200, blank=True, null=True)
    facebook_profile_url = models.URLField(
        max_length=1500, blank=True, null=True)
    youtube_profile_url = models.URLField(
        max_length=1500, blank=True, null=True)

    @property
    def full_name(self):
        return "{} {}".format(self.first_name, self.last_name)

    def __str__(self):
        return self.full_name


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField()
    is_featured = models.BooleanField(default=False)

    @property
    def featured_videos(self):
        return self.videos.filter(featured_category=True)

    def __str__(self):
        return self.name


class Conference(models.Model):
    name = models.CharField(max_length=200)
    slug = models.CharField(max_length=200)
    site_url = models.URLField(max_length=1500)

    def __str__(self):
        return self.name


class Video(TimeStampedModel):
    title = models.CharField(max_length=200)
    youtube_video_id = models.CharField(max_length=200)
    speaker = models.ForeignKey(Speaker)
    description = models.TextField(blank=True, null=True)

    conference = models.ForeignKey(Conference)
    year = models.PositiveSmallIntegerField()
    categories = models.ManyToManyField(Category, related_name='videos')

    featured_category = models.BooleanField(default=False)

    @property
    def youtube_watch_url(self):
        return "https://www.youtube.com/watch?v={}".format(
            self.youtube_video_id)

    @property
    def youtube_embed_url(self):
        return "https://www.youtube.com/embed/{}".format(
            self.youtube_video_id)

    def __str__(self):
        return "{title} - {speaker} ({conference} {year})".format(
            title=self.title,
            speaker=self.speaker,
            conference=self.conference,
            year=self.year)


class HomeFeaturedVideo(TimeStampedModel):
    video = models.ForeignKey(Video)

    def __str__(self):
        return "Featured: {}".format(self.video)

django_video/curated_videos/views.py
from django.views.generic import TemplateView
from .models import Video, HomeFeaturedVideo, Category, Conference, Speaker
from django.shortcuts import get_object_or_404


class HomePageView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super(HomePageView, self).get_context_data(**kwargs)
        home_featured_video = HomeFeaturedVideo.objects.latest('id')

        featured_categories = Category.objects.filter(is_featured=True)

        context['home_featured_video'] = home_featured_video.video
        context['featured_categories'] = featured_categories
        return context


class SlugListingView(TemplateView):
    template_name = 'listing.html'
    MODEL_CLASS = None
    DEFAULT_ARUGMENT_NAME = 'slug'

    def get_obj_display_name(self, obj):
        return obj.name

    def get_context_data(self, **kwargs):
        context = super(SlugListingView, self).get_context_data(**kwargs)
        filter_argument = kwargs[self.DEFAULT_ARUGMENT_NAME]
        filter_criteria = {
            self.DEFAULT_ARUGMENT_NAME: filter_argument
        }
        listing = get_object_or_404(self.MODEL_CLASS, **filter_criteria)
        context['listing'] = listing
        context['display_listing_name'] = self.get_obj_display_name(listing)
        context['videos'] = self.get_videos(listing)
        return context


class CategoryListingView(SlugListingView):
    MODEL_CLASS = Category

    def get_videos(self, obj):
        return obj.videos.all()


class SpeakerListingView(SlugListingView):
    MODEL_CLASS = Speaker
    DEFAULT_ARUGMENT_NAME = 'id'

    def get_obj_display_name(self, obj):
        return obj.full_name

    def get_videos(self, obj):
        return Video.objects.filter(speaker=obj)


class ConferenceListingView(SlugListingView):
    MODEL_CLASS = Conference

    def get_videos(self, obj):
        return Video.objects.filter(conference=obj)

templates/about.html
{% extends "bare.html" %}
{% block body %}
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <h1>About</h1>
      <hr>
      <p><a href="/">django.video</a> 📹 is a collection of curated videos about the <a href="https://www.djangoproject.com">Django Web Framework</a> put together by people from <strong><a href="https://rmotr.com">rmotr.com</a></strong> 🐶.</p>
      <p>As part of our <a href="https://rmotr.com/web-development-with-django">Web Development with Django</a> course, we give our students good resources from different Django conferences. Django has an amazing community and experts from everywhere give talks about different topics. 🙌</p>
      <p>It's also a great resource for learning Django development 🤓. The project is structured in a way that <strong>makes it easy to walk through</strong> the different phases of the project development.</p>
      <p>We know that most of you trying to learn Django are <strong>tired of dumb tutorials that fall short</strong>. This project can provide a comprehensive guide and demonstration of what a production-ready Django project looks like.</p>
      <p>This is an free and open source project, developed with <a href="https://www.python.org/">Python 3</a> and <a href="https://www.djangoproject.com">Django</a>. If you're interested checkout the <a href="https://github.com/rmotr/django-video">Github project page</a>. It's ready to be deployed on <a href="https://www.heroku.com">Heroku</a>, we'll build a guide on how to do it soon, <a href="https://twitter.com/rmotr_com">stay tunned</a>.</p>
      <p>If you have any question, feel free to contact us at <a href="mailto:questions@rmotr.com">questions@rmotr.com</a> 📫 and follow us on <a href="https://twitter.com/rmotr_com">twitter</a> 🐦.</p>
      <p>Finally, if you'd like to suggest a video to add, please submit an issue using <a href="https://github.com/rmotr/django-video/issues/new">this Github page</a>.</p>
    </div>
  </div>

  {% include 'partials/footer.html' with extra_classes="sticky"%}
</div>

{% endblock %}

templates/analytics.html
{% if GOOGLE_ANALYTICS %}
<script type="text/javascript">
    var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
    document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
</script>
<script type="text/javascript">
    try {
        var pageTracker = _gat._getTracker("{{ GOOGLE_ANALYTICS }}");
        pageTracker._trackPageview();
    } catch (err) {}
</script>
{% endif %} {% if GAUGES_ANALYTICS %}
<script type="text/javascript">
    var _gauges = _gauges || [];
    (function() {
        var t = document.createElement('script');
        t.type = 'text/javascript';
        t.async = true;
        t.id = 'gauges-tracker';
        t.setAttribute('data-site-id', '{{ GAUGES_ANALYTICS }}');
        t.src = '//secure.gaug.es/track.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
    })();
</script>
{% endif %}

templates/bare.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    {% block head %}
      <title>{% block title %}{{ SITENAME }}{% endblock title %}</title>
      <meta charset="utf-8" />
    {% endblock head %}

    <link href="https://fonts.googleapis.com/css?family=Yellowtail" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">

    <!-- Custom styles -->
    <link href="{% static "css/main.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
    {% block body %}{% endblock %}
    {% block scripts %}
      <script src="https://code.jquery.com/jquery-2.2.4.min.js"
              integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
              crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
              integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
              crossorigin="anonymous"></script>

      <!-- Custom Scripts -->
      <script src="{% static "js/main.js" %}"></script>

    {% endblock %}
    {% include 'analytics.html' %}
</body>

</html>

templates/base.html
{% extends "bare.html" %}
{% load static %}
{% block body %}
{% include 'partials/fork-github-ribbon.html' %}
<!-- Page Content -->
<div class="container">
    <div class="row">
      <div class="col-xs-12 logo-title-container">
        <a href="/" class='logo-link'>
          <img class='logo' src="{% static "images/django-logo-positive.png" %}" alt='Django logo'>
          <h1 class='logo-video-title'>.video</h1>
        </a>
        <p class='curated-legend'><b>curated by <a href="https://rmotr.com">rmotr.com</a></b></p>
      </div>
    </div>
    {% block content %}{% endblock %}
    {% include 'partials/footer.html' %}

</div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Featured Video</h1>
    </div>
</div>
<!-- /.row -->

<div class="row" class='home-featured-video-container'>
    <div class="col-md-8">
        {% include 'partials/youtube-embed-iframe.html' with video=home_featured_video %}
    </div>
    <div class="col-md-4">
        <h3 class='title-and-speaker'>{{home_featured_video.title}} <br><small><a href="{% url 'curated_videos:speaker-listing' home_featured_video.speaker.id %}">{{ home_featured_video.speaker.full_name }}</a></small></h3>
        <p>{{ home_featured_video.description }}</p>
        {% include 'partials/video-badges.html' with video=home_featured_video %}
        <p class='permalink'>
          <a href="#">Permalink</a>
        </p>
    </div>
</div>
<!-- /.row -->
{% for category in featured_categories %}
  {% if category.featured_videos %}
    <div class="row">
        <div class="col-lg-12">
            <h4 class="page-header"><strong>{{category.name}} -</strong> Featured Videos</h4>
        </div>
        {% for video in category.featured_videos %}
        <div class="col-sm-3 col-xs-6 category-featured-video-container">
          <h6 class='video-title'>{{ video.title }}</h6>
            {% include 'partials/youtube-embed-iframe.html' with video=video %}
            <h4 class='speaker-name'><small><a href="{% url 'curated_videos:speaker-listing' video.speaker.id %}">{{ video.speaker.full_name }}</a></small></h4>
            <div>
              {% include 'partials/video-badges.html' with video=video %}
            </div>
        </div>
        {% endfor %}
    </div>
  {% endif %}
{% endfor %}

<!-- /.row -->
{% endblock %}

templates/listing.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><strong>{{ display_listing_name }} -</strong> Videos</h1>
    </div>
</div>
<div class="row">
  {% for video in videos %}
    <div class="col-sm-3 col-xs-6 category-featured-video-container">
      <h6 class='video-title'>{{ video.title }}</h6>
        {% include 'partials/youtube-embed-iframe.html' with video=video %}
        <h4 class='speaker-name'><small><a href="{% url 'curated_videos:speaker-listing' video.speaker.id %}">{{ video.speaker.full_name }}</a></small></h4>
        <div>
          {% include 'partials/video-badges.html' with video=video %}
        </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

templates/partials/footer.html
<footer class="{{extra_classes}}">
    <div class="row">
        <div class="col-xs-12">
            <p>django.video is kindly brought to you by <strong><a href="https://rmotr.com">rmotr.com</a></strong>. Read more about it <a href="{% url 'about' %}">here</a>.</p>
        </div>
    </div>
</footer>

templates/partials/fork-github-ribbon.html
<a href="https://github.com/rmotr/django-video" target='_blank'><img style="position: absolute; top: 0; right: 0; border: 0;z-index:1000" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>

templates/partials/video-badges.html
<a href="{% url 'curated_videos:conference-listing' video.conference.slug %}"><span class="label label-default">{{ video.conference.slug }}</span></a>
<span class="label label-primary">{{ video.year }}</span>
{% for category in video.categories.all %}
  <a href="{% url 'curated_videos:category-listing' category.slug %}"><span class="label label-success">{{ category.name }}</span></a>
{% endfor %}

templates/partials/youtube-embed-iframe.html
<div class="youtube" style='' id="{{video.youtube_video_id}}">
  <img src="http://i.ytimg.com/vi/{{video.youtube_video_id}}/0.jpg" style='width: 100%' alt="">
</div>